name: mochi
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_riverpod: ^2.1.3
  jovial_svg: ^1.1.9
  socket_io_client: ^2.0.1
  font_awesome_flutter: ^10.3.0
  firebase_core: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  assets_indexer: ^0.0.9
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/brand/

  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 800
