name: mochi
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  introduction_screen: ^3.1.4
  jovial_svg: ^1.1.9
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.0+1
  socket_io_client: ^2.0.1
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter  
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brand/logo_mascot.png"
  web:
    generate: true
    image_path: "assets/brand/logo_mascot.png"

flutter:
  uses-material-design: true

  assets:
    - assets/brand/
    - assets/graphics/
    - assets/graphics/onboarding/

  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 800
