name: mochi
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  buttons_tabbar: ^1.3.6
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  introduction_screen: ^3.1.4
  image_picker: ^0.8.6+4
  jovial_svg: ^1.1.9
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  http: ^0.13.5
  font_awesome_flutter: ^10.3.0
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.0+1
  sliding_up_panel: ^2.0.0+1
  socket_io_client: ^2.0.1
  flutter_launcher_icons: ^0.12.0
  filter_list: ^1.0.2
  camera: ^0.10.3+1
  video_player: ^2.5.2
  path_provider: ^2.0.13
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  path_drawing: ^1.0.1
  collection: ^1.17.0
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/brand/logo_mascot.png"
  web:
    generate: true
    image_path: "assets/brand/logo_mascot.png"

flutter:
  uses-material-design: true

  assets:
    - lib/.env
    - assets/brand/
    - assets/graphics/
    - assets/graphics/onboarding/
    - assets/graphics/placeholder/

  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 800
