// ignore_for_file: constant_identifier_names

List<String> interestsList = [
  "Acting",
  "Action games",
  "Action movies",
  "Adventure travel",
  "Advertising",
  "Agriculture",
  "Air travel",
  "Alcoholic beverages",
  "American football",
  "Animated movies",
  "Anime movies",
  "Architecture",
  "Arts and music",
  "Association football (Soccer)",
  "Audio equipment",
  "Auto racing",
  "Automobiles",
  "Aviation",
  "Baking",
  "Ballet",
  "Banking",
  "Barbecue",
  "Bars",
  "Baseball",
  "Basketball",
  "Beaches",
  "Beauty",
  "Beauty salons",
  "Beer",
  "Beverages",
  "Birds",
  "Blues music",
  "Board games",
  "Boating",
  "Boats",
  "Bodybuilding",
  "Bollywood movies",
  "Books",
  "Boutiques",
  "Browser games",
  "Business",
  "Business and Industry",
  "Camcorders",
  "Cameras",
  "Camping",
  "Car rentals",
  "Card games",
  "Casino games",
  "Cats",
  "Charity and causes",
  "Children's Clothing",
  "Chinese cuisine",
  "Chocolate",
  "Classical music",
  "Clothing",
  "Coffee",
  "Coffeehouses",
  "College Football",
  "Comedy movies",
  "Comics",
  "Community issues",
  "Computer memory",
  "Computer monitors",
  "Computer processors",
  "Computer servers",
  "Computers",
  "Concerts",
  "Construction",
  "Consumer electronics",
  "Cooking",
  "Cosmetics",
  "Country music",
  "Coupons",
  "Crafts",
  "Credit cards",
  "Cruises",
  "Cuisine",
  "Current events",
  "Dance",
  "Dance music",
  "Dancehalls",
  "Dating",
  "Design",
  "Desktop computers",
  "Desserts",
  "Digital Marketing",
  "Diners",
  "Discount stores",
  "Display advertising",
  "Distilled beverage",
  "Do it yourself (DIY)",
  "Documentary movies",
  "Dogs",
  "Drama movies",
  "Drawing",
  "Dresses",
  "Drums",
  "E-book readers",
  "E-books",
  "Economics",
  "Ecotourism",
  "Electric vehicle",
  "Electronic music",
  "Email marketing",
  "Energy drinks",
  "Engineering",
  "Entertainment",
  "Entrepreneurship",
  "Environmentalism",
  "Family",
  "Family and relationships",
  "Fantasy movies",
  "Fashion accessories",
  "Fashion design",
  "Fast casual restaurants",
  "Fast food",
  "Fast food restaurants",
  "Fatherhood",
  "Fiction books",
  "Fine art",
  "First-person shooter games",
  "Fish",
  "Fishing",
  "Fitness and wellness",
  "Food",
  "Food and drink",
  "Fragrances",
  "Free software",
  "French cuisine",
  "Friendship",
  "Furniture",
  "Gambling",
  "Game consoles",
  "Games",
  "Gardening",
  "German cuisine",
  "Golf",
  "Gospel music",
  "GPS devices",
  "Graphic design",
  "Greek cuisine",
  "Guitar",
  "Hair products",
  "Handbags",
  "Hard drives",
  "Health care",
  "Heavy metal music",
  "Higher education",
  "Hip hop music",
  "Hobbies and activities",
  "Home and Garden",
  "Home Appliances",
  "Home Improvement",
  "Horror movies",
  "Horseback riding",
  "Horses",
  "Hotels",
  "Hunting",
  "Hybrids",
  "Indian cuisine",
  "Insurance",
  "Interior design",
  "Investment",
  "Investment banking",
  "Italian cuisine",
  "Japanese cuisine",
  "Jazz music",
  "Jewelry",
  "Juice",
  "Korean cuisine",
  "Lakes",
  "Latin American cuisine",
  "Law",
  "Literature",
  "Live events",
  "Luxury goods",
  "Magazines",
  "Management",
  "Manga",
  "Marathons",
  "Marketing",
  "Marriage",
  "Massively multiplayer online role-playing games",
  "Massively multiplayer online games",
  "Meditation",
  "Men's Clothing",
  "Mexican cuisine",
  "Middle Eastern cuisine",
  "Military",
  "Minivans",
  "Mobile phones",
  "Mortgage loans",
  "Motherhood",
  "Motorcycles",
  "Mountain biking",
  "Mountains",
  "Movies",
  "Music",
  "Music festivals",
  "Music videos",
  "Musical theatre",
  "Mystery fiction",
  "Nature",
  "Network storage",
  "Newspapers",
  "Nightclubs",
  "Non-fiction books",
  "Nursing",
  "Online",
  "Online advertising",
  "Online banking",
  "Online games",
  "Online poker",
  "Online shopping",
  "Organic food",
  "Outdoor recreation",
  "Painting",
  "Parenting",
  "Parties",
  "Performing arts",
  "Personal Finance",
  "Pet food",
  "Pets",
  "Photography",
  "Physical exercise",
  "Physical therapy",
  "Physical fitness",
  "Pizza",
  "Plays",
  "Politics",
  "Politics and social issues",
  "Pop music",
  "Portable media players",
  "Projectors",
  "Puzzle video games",
  "Rabbits",
  "Racing games",
  "Reading",
  "Real estate",
  "Recipes",
  "Religion",
  "Reptiles",
  "Restaurants",
  "Retail",
  "Retail banking",
  "Rhythm and blues music",
  "Rock music",
  "Role-playing games",
  "Romance novels",
  "Running",
  "RVs",
  "Sales",
  "Science",
  "Science fiction movies",
  "Scooters",
  "Sculpture",
  "Seafood",
  "Search engine optimization",
  "Shoes",
  "Shooter games",
  "Shopping",
  "Shopping and fashion",
  "Shopping malls",
  "Simulation games",
  "Singing",
  "Skiing",
  "Small business",
  "Smartphones",
  "Snowboarding",
  "Social media",
  "Social media marketing",
  "Soft drinks",
  "Software",
  "Soul music",
  "Spanish cuisine",
  "Spas",
  "Sports",
  "Sports and outdoors",
  "Sports games",
  "Strategy games",
  "Sunglasses",
  "Surfing",
  "Sustainability",
  "SUVs",
  "Swimming",
  "Tablet computers",
  "Tattoos",
  "Tea",
  "Technology",
  "Televisions",
  "Tennis",
  "Thai cuisine",
  "Theatre",
  "Theme parks",
  "Thriller movies",
  "Tourism",
  "Toys",
  "Travel",
  "Triathlons",
  "Trucks",
  "TV",
  "TV comedies",
  "TV game shows",
  "TV reality shows",
  "TV talk shows",
  "Vacations",
  "Veganism",
  "Vegetarianism",
  "Vehicles",
  "Veterans",
  "Video games",
  "Vietnamese cuisine",
  "Volleyball",
  "Volunteering",
  "Web design",
  "Web development",
  "Web hosting",
  "Weddings",
  "Weight training",
  "Wine",
  "Women's Clothing",
  "Word games",
  "Writing",
  "Yoga",
];
